micronaut.application.name=jsolex-ui-api
micronaut.router.static-resources.css.enabled=false
micronaut.router.static-resources.js.enabled=false
micronaut.router.static-resources.img.enabled=false
micronaut.router.static-resources.default.enabled=false
micronaut.router.static-resources.openapi.mapping=/openapi/**
micronaut.router.static-resources.openapi.paths=classpath\:META-INF/swagger
micronaut.serde.serialization.inclusion=ALWAYS
micronaut.views.enabled=false
